// <auto-generated />
using System;
using ArkServerManager.Worker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArkServerManager.Worker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427224541_InitialMvpSchema")]
    partial class InitialMvpSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("ArkServerManager.Worker.Data.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("LogBlob")
                        .HasColumnType("TEXT")
                        .HasColumnName("log_blob");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_jobs_server_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("ArkServerManager.Worker.Data.Entities.ServerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GamePort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_port");

                    b.Property<string>("InstallRoot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("install_root");

                    b.Property<Guid?>("LastJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_job_id");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("map_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("Pid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pid");

                    b.Property<int>("QueryPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("query_port");

                    b.Property<string>("RconPassword")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rcon_password");

                    b.Property<int>("RconPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rcon_port");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("ArkServerManager.Worker.Data.Entities.JobEntity", b =>
                {
                    b.HasOne("ArkServerManager.Worker.Data.Entities.ServerEntity", "Server")
                        .WithMany("Jobs")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ArkServerManager.Worker.Data.Entities.ServerEntity", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
